name: Upload File to S3

on:
  push:
    branches:
      - '**'  # all branches

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment-specific variables
        id: set-vars
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=development" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.VERSION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VERSION_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Upload file to S3
        run: |
          aws s3 cp appversion.json s3://${{ vars.VERSION_S3_BUCKET }}/appversion.json
